version: "3.9"
services:
    main:
        container_name: jury-main
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - REACT_APP_JURY_NAME=${JURY_NAME}
            - PORT=8000
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                - REACT_APP_JURY_NAME=${JURY_NAME}
                - REACT_APP_JURY_URL=/api
                - REACT_APP_HUB=${HEHE:-}
        ports:
            - ${PORT:-8000}:8000
