version: "3.9"
services:
    rust:
        container_name: jury-main
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - PORT=8000
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                - REACT_APP_JURY_NAME=${JURY_NAME}
                - REACT_APP_JURY_URL=/api
                - REACT_APP_HUB=${HEHE:-}
        ports:
            - 8000:8000
