name: Bug Report
description: Report a bug or something that is wrong
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes: 
      value: Thanks for filling out this bug report! Please let us know what went wrong below.
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: What is happening that doesn't seem right, in as much detail as possible.
      placeholder: ex. The text box clips out of the edge of the screen
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Give clear steps on how to reproduce the bug you found
      placeholder: 1. \n 2. \n 3. \n 4. \n
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device(s) are you seeing this issue on?
      multiple: true
      options:
        - Linux Computer
        - Windows Computer
        - Mac Computer
        - Android Mobile Device
        - iOS Mobile Device
        - Other Device (list below)
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you seeing this issue on?
      multiple: true
      options:
        - Firefox Desktop
        - Chromium Desktop (Chrome, Brave, Edge, Arc, Opera)
        - Safari Desktop
        - Firefox Mobile
        - Chromium Mobile
        - Safari Mobile
        - Other Browser (list below)
  - type: textarea
    id: solutions
    attributes:
      label: Possible Solutions
      description: List possible solutions to the bug, if any
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Please attach any additional information not included above to help us better address this issue; this can be images, videos, or logs (optional)
