name: Question
description: Ask a question or open discussion on a topic
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: If you have any questions or want to create an open discussion about a feature, please enter it here!
  - type: textarea
    id: question
    attributes:
      label: What is your question? Describe in detail.
      description: A clear and concise description of what the question is.
      placeholder: ex. Should this screen be changed to...?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Put additional context for your question here. This can be screenshots, code, or anything else!
